=== yelena88/homework-book-2/src/com/lena/hw/book2/ex8/Ex8_My_Task/car_catalog.dtd
<?xml version = "1.0"  encoding = "utf-8"?>
        <!--Для xml, сделанного в предыдущем задании, -->
        <!--создайте DTD с жестко заданными значениями -->
        <!-- параметра units тега point -->
        <!--Использована внешняя декларация DTD -->
        <!ELEMENT car_catalog (car+)>

        <!ELEMENT car (year, make, model, color, engine,
                number_of_doors, accessories)>

        <!ELEMENT year (#PCDATA)>
        <!ELEMENT make (#PCDATA)>
        <!ELEMENT model (#PCDATA)>
        <!ELEMENT color (#PCDATA)>
        <!ELEMENT engine (Petrol | Diesel)>

        <!ELEMENT Petrol (#PCDATA)>
        <!ELEMENT Diesel (#PCDATA)>

        <!ATTLIST Petrol number_of_cylinders CDATA #REQUIRED>
        <!ATTLIST Petrol fuel_system CDATA #REQUIRED>
        <!ATTLIST Petrol transmission_type CDATA #REQUIRED>
        <!ATTLIST Petrol number_of_gears CDATA #REQUIRED>
        <!ATTLIST Petrol drive_train CDATA #REQUIRED>
        <!ATTLIST Petrol fuel_tank_capacity CDATA #REQUIRED>
        <!ATTLIST Petrol maximum_speed CDATA #REQUIRED>

        <!ATTLIST Diesel number_of_cylinders CDATA #REQUIRED>
        <!ATTLIST Diesel fuel_system CDATA #REQUIRED>
        <!ATTLIST Diesel transmission_type CDATA #REQUIRED>
        <!ATTLIST Diesel number_of_gears CDATA #REQUIRED>
        <!ATTLIST Diesel drive_train CDATA #REQUIRED>
        <!ATTLIST Diesel fuel_tank_capacity CDATA #REQUIRED>
        <!ATTLIST Diesel maximum_speed CDATA #REQUIRED>

        <!ELEMENT number_of_doors (#PCDATA)>
        <!ELEMENT accessories (Items)>

        <!ELEMENT Items (#PCDATA)>

        <!ATTLIST Items radio CDATA #REQUIRED>
        <!ATTLIST Items air_conditioner CDATA #REQUIRED>
        <!ATTLIST Items cruise_control CDATA #REQUIRED>
        <!ATTLIST Items climate_control CDATA #REQUIRED>
        <!ATTLIST Items rear_parking_sensor CDATA #REQUIRED>
        <!ATTLIST Items cornering_lights CDATA #REQUIRED>

=== yelena88/homework-book-2/src/com/lena/hw/book2/ex8/Ex8_My_Task/Car_catalog.xml
<?xml version = "1.0"  encoding = "utf-8"?>
<!DOCTYPE car_catalog SYSTEM "car_catalog.dtd">
<car_catalog>
    <car>
        <year>2014</year>
        <make>BMV</make>
        <model>X6</model>
        <color>Black Sapphire (metallic)</color>
        <engine>
            <Petrol number_of_cylinders="6 cylinder" fuel_system="TwinPower Turbo Inline"
                    transmission_type="Automatic" number_of_gears="8 speed" drive_train="4WD"
                    fuel_tank_capacity="85.0 liters" maximum_speed="240 Kmph"/>
        </engine>
        <number_of_doors>5</number_of_doors>
        <accessories>
            <Items radio="yes" air_conditioner="yes" cruise_control="yes"
                   climate_control="yes" rear_parking_sensor="yes" cornering_lights="yes"/>
        </accessories>
    </car>
    <car>
        <year>2016</year>
        <make>Audi</make>
        <model>Q7</model>
        <color>Ice Silver</color>
        <engine>
            <Diesel number_of_cylinders="6 cylinder"
                    fuel_system="Common Rail Injection System And Turbocharging"
                    transmission_type="Automatic" number_of_gears="8 speed" drive_train="AWD"
                    fuel_tank_capacity="75.0 liters" maximum_speed="234 Kmpl"/>
        </engine>
        <number_of_doors>5</number_of_doors>
        <accessories>
            <Items radio="yes" air_conditioner="yes"
                   cruise_control="yes" climate_control="yes"
                   rear_parking_sensor="yes" cornering_lights="no"/>
        </accessories>
    </car>
    <car>
        <year>2016</year>
        <make>Land Rover</make>
        <model>Range Rover Sport</model>
        <color>Blue</color>
        <engine>
            <Petrol number_of_cylinders="6 cylinder" fuel_system="3.0L V-Type Engine"
                    transmission_type="Automatic" number_of_gears="8 speed" drive_train="4WD"
                    fuel_tank_capacity="105.0 liters" maximum_speed="210 Kmpl"/>
        </engine>
        <number_of_doors>5</number_of_doors>
        <accessories>
            <Items radio="yes" air_conditioner="yes"
                   cruise_control="yes" climate_control="yes"
                   rear_parking_sensor="yes" cornering_lights="no"/>
        </accessories>
    </car>
</car_catalog>
